[build]
publish = "."
functions = "netlify/functions"

# Route API calls to Netlify Function
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true

# Route dashboard path to static file
[[redirects]]
from = "/dashboard"
to = "/dashboard.html"
status = 200
