[build]
command = "npm i"
publish = "."

[functions]
node_bundler = "esbuild"
external_node_modules = ["openai", "pg", "pgvector"]

# Route API calls to Netlify Function
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true

# Route dashboard path to static file
[[redirects]]
from = "/dashboard"
to = "/dashboard.html"
status = 200
