service: gasable-hub

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  timeout: 29
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    OPENAI_MODEL: ${env:OPENAI_MODEL, 'gpt-5-mini'}
    OPENAI_EMBED_MODEL: ${env:OPENAI_EMBED_MODEL, 'text-embedding-3-small'}
    DATABASE_URL: ${env:DATABASE_URL}
    CORS_ORIGINS: ${env:CORS_ORIGINS, '*'}

functions:
  api:
    handler: lambda_function.handler
    events:
      - httpApi: '*'

package:
  patterns:
    - '!**/*'
    - 'webapp.py'
    - 'gasable_hub/**'
    - 'lambda_function.py'
    - 'requirements.txt'


